### ISSUE TITLE
Restore Ubuntu Core/Snap support

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/wott-agent-snap#5]
We broke this some time ago. Let's:

 * Fix the build
 * Upgrade the base image to Core 18

**Comment by a-martynovich** [comment]
@vpetersson You decided to upgrade to core 18 only because of nmap. Since we don't use nmap anymore, perhaps we don't need to upgrade?

**Comment by vpetersson** [comment]
Closed in favor of #4. 

> @vpetersson You decided to upgrade to core 18 only because of nmap. Since we don't use nmap anymore, perhaps we don't need to upgrade?

I've already toyed with the upgrade to core18 and I think it should work. No reason to stick to 16 as 18 has a lot more benefits.
